[project]
protostar-version = "0.13.0"
lib-path = "lib"
cairo-path = ["lib", "./lib/cairo_contracts/src"]

[contracts]
verifier = ["src/main.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]